version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Docker/postgres.Dockerfile
    image: icybadger/powerscraper-postgres:1.0.0
    restart: no # Testvalue
    volumes:
      - pg_db:/var/lib/postgresql/data:rw
    networks:
      - private_net
    ports:
      - '5432:5432'
    environment:
      - PGPASSWORD=Pass123456789!
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pass123456789!

  app:
    build:
      context: .
      dockerfile: Docker/app.Dockerfile
    image: icybadger/powerscraper-app:1.0.0
    restart: no
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    networks:
      - private_net
    ports:
      - '6538:6538'

networks:
  private_net:
    driver: bridge

volumes:
  pg_db:
    driver: local